# Generated by Django 3.2.9 on 2021-12-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_uno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Minino', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_dos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Minino', max_length=100)),
                ('referencia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ejemplo_form.tabla_uno')),
            ],
        ),
    ]
