# Generated by Django 3.2.9 on 2021-12-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_word', models.CharField(default='Sample', max_length=200)),
                ('clue', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
