# Generated by Django 3.2.9 on 2021-11-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='secure_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
